/:
  controller: Security
  action: homePage

/bo/dashboard:
  controller: Main
  action: home
  security: true
  # roles: [admin, editor]

/register:
  controller: Security
  action: register

/activate-account:
  controller: Security
  action: activateAccount

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/bo/pages:
  controller: Posts
  action: allPages
  security: true
  # roles: [admin, editor]

/bo/pages/add-page:
  controller: Posts
  action: addPage
  security: true
  # roles: [admin, editor]

/bo/pages/new-page:
  controller: Posts
  action: newPage
  security: true
  # roles: [admin, editor]

/bo/pages/edit-page:
  controller: Posts
  action: editPage
  security: true
  # roles: [admin, editor]

/bo/settings:
  controller: SiteSetting
  action: index
  security: true
  # roles: [admin]

/bo/user:
  controller: User
  action: allUsers
  security: true
  # roles: [admin, editor]

/bo/user/view-user:
  controller: User
  action: viewUser
  security: true
  # roles: [admin, editor]

/bo/user/edit-user:
  controller: User
  action: editUser
  security: true
  # roles: [admin]

/bo/user/edit-password:
  controller: User
  action: editPassword
  security: true
  # roles: [admin]

/recover-password:
  controller: Security
  action: requestResetPassword

/reset-password:
  controller: Security
  action: resetPassword

/bo/articles:
  controller: Posts
  action: allArticles
  security: true
  # roles: [admin, editor]

/bo/articles/add-article:
  controller: Posts
  action: addArticles
  security: true
  # roles: [admin, editor]

/bo/articles/new-article:
  controller: Posts
  action: newArticle
  security: true
  # roles: [admin, editor]

/bo/articles/update-article:
  controller: Posts
  action: updateArticle
  security: true
  # roles: [admin, editor]

/bo/articles/edit-article:
  controller: Posts
  action: editArticle
  security: true
  # roles: [admin, editor]

/run:
  controller: Install
  action: run

